name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/undefined/Policyholder 360.json" -e "16863297-e6ff3c40-5e1a-4061-9e21-e10657326768" --integration-id "147730-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 1e10ef15-8ab2-4485-aa84-370363406c1c --integration-id 147730
