# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm install -g newman
    npm install -g newman-reporter-html
    newman run "postman/collections/Policyholder-360_5d94bf12-ca25-4683-88bc-6c6132d7e782.json" -e "postman/Policyholder-Mock.postman_environment.json" --reporters cli,html
  displayName: 'build with newman'
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
# Publish build artifacts
# Publish build artifacts to Azure Pipelines or a Windows file share
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Report'
    publishLocation: 'Container'
    #targetPath: # Required when publishLocation == FilePath